[project]
name = "career-conversation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.31.0",
    "openai>=1.82.0",
    "pypdf>=5.5.0",
    "requests>=2.32.3",
]
